services:
  nginx:
    image: nginx:1.28
    container_name: drupal_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./gal-cruise:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - drupal-net

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    working_dir: /var/www/html/web
    container_name: drupal_php
    restart: unless-stopped
    volumes:
      - ./gal-cruise:/var/www/html/
    depends_on:
      - db
    networks:
      - drupal-net
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}

  db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: drupal_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - drupal-net
volumes:
  db_data:
networks:
  drupal-net: